Tech 3035 add the ability to take a deposit
clockwork-marketing-uk/module-holiday-park pull request #25
Opened 2024-04-26 12:02 UTC by TomClockwork

2024-04-26 12:02 UTC, TomClockwork commented on src/Controllers/BookingController.php
> +    return ($request->paying_deposit && $request->paying_deposit == "true");
string because it comes from the form where you cannot set a proper bool

2024-05-01 09:31 UTC, jackpricenice requested changes

2024-05-01 09:31 UTC, jackpricenice commented on src/migrations/2024_04_26_135100_add_deposit_column_to_booking_payments_table.php
> +  {
If statement

2024-05-01 11:03 UTC, GrantFS approved these changes

2024-05-01 11:03 UTC, GrantFS commented on src/resources/js/modules/optionals/holiday-park/booking/booking-components/payment-options.js
> +  // toggleAccordion()
remove?

2024-05-01 11:26 UTC, jackpricenice approved these changes

2024-05-01 11:26 UTC, merged